/**
 * Pipeline Status and Configuration Types
 *
 * TypeScript interfaces for automation pipeline status tracking
 * and configuration management.
 */

export interface PipelineStatus {
  /** GitHub Actions workflow run identifier */
  workflowRunId: string;
  /** Git commit that initiated the pipeline */
  triggerCommit: string;
  /** Current stage of execution */
  pipelineStage: PipelineStage;
  /** Map of job names to their execution status */
  jobStatuses: Record<string, JobStatus>;
  /** Pipeline execution start timestamp */
  startTime: string;
  /** Pipeline completion timestamp (if finished) */
  endTime?: string;
  /** Array of error messages if failures occurred */
  errorLogs: ErrorLog[];
  /** Map of generated artifact names to download URLs */
  artifactUrls: Record<string, string>;
}

export type PipelineStage =
  | 'setup'
  | 'validate'
  | 'build'
  | 'release'
  | 'publish'
  | 'completed'
  | 'failed';

export interface JobStatus {
  /** Job execution status */
  status: 'pending' | 'in_progress' | 'success' | 'failure' | 'cancelled';
  /** Job start timestamp */
  startedAt?: string;
  /** Job completion timestamp */
  completedAt?: string;
  /** Job-specific error message if failed */
  errorMessage?: string;
  /** URL to job logs */
  logsUrl?: string;
}

export interface ErrorLog {
  /** Timestamp of error occurrence */
  timestamp: string;
  /** Error severity level */
  level: 'error' | 'warning' | 'info';
  /** Error message */
  message: string;
  /** Job or step that generated the error */
  source: string;
  /** Additional error context */
  details?: Record<string, unknown>;
}

export interface ReleaseArtifacts {
  /** Semantic version string generated by semantic-release */
  version: string;
  /** Git tag created for the release */
  gitTag: string;
  /** Markdown-formatted changelog content */
  releaseNotes: string;
  /** URL to published package on npm registry */
  npmPackageUrl: string;
  /** URL to GitHub release page */
  githubReleaseUrl: string;
  /** Array of file paths included in release */
  buildArtifacts: string[];
  /** ISO timestamp of successful publication */
  publishTimestamp: string;
  /** Git commit SHA that triggered the release */
  commitSha: string;
}

export interface SemanticReleaseConfig {
  /** Branch configurations for release triggers */
  branches: (string | BranchConfig)[];
  /** Ordered array of semantic-release plugins */
  plugins: (string | [string, ...unknown[]])[];
  /** Git repository URL for release context */
  repositoryUrl?: string;
  /** Template for git tag naming */
  tagFormat?: string;
  /** Test mode without actual publishing */
  dryRun?: boolean;
  /** Enable verbose logging output */
  debug?: boolean;
}

export interface BranchConfig {
  /** Branch name or pattern */
  name: string;
  /** Prerelease identifier */
  prerelease?: boolean | string;
}

export interface WorkflowEnvironment {
  /** Node.js version to use */
  nodeVersion: string;
  /** Operating system for runners */
  os: 'ubuntu-latest' | 'windows-latest' | 'macos-latest';
  /** Package manager to use */
  packageManager: 'npm' | 'yarn' | 'pnpm';
  /** Registry URL for npm publishing */
  registry: string;
}

export interface WorkflowSecrets {
  /** npm authentication token */
  NPM_TOKEN: string;
  /** GitHub token for releases */
  GITHUB_TOKEN: string;
}

export interface ValidationResult {
  /** Overall validation status */
  isValid: boolean;
  /** Array of validation errors */
  errors: string[];
  /** Array of validation warnings */
  warnings: string[];
  /** Validation execution timestamp */
  timestamp: string;
}

export interface PublishResult {
  /** Whether publish was successful */
  success: boolean;
  /** Published package version */
  version?: string;
  /** npm package URL */
  packageUrl?: string;
  /** Error message if failed */
  error?: string;
  /** Publish timestamp */
  timestamp: string;
}
